# Data Cleaning in Pandas - Introduction

## Introduction

In this section, you will learn invaluable skills that will form the foundation of your data processing work. Before you can apply machine learning algorithms or do interesting analyses, you often must clean and transform your data into a suitable format. Such initial data wrangling processes are often referred to as Extract Transform Load (ETL). Our primary tool of choice for performing ETL and basic analyses will be the Pandas package.

## Why ETL?

ETL is an essential first step to data analysis and data science. It also will form the foundation for exploratory data analysis. Often, you will be thrown a dataset that you have little to no information about. In these cases, your first step is to explore the data and get familiar with it. What are the columns? How many observations do you have? Are there missing values? Any outliers? If we have user-level data, how can we explore aggregate trends along features like gender, race, or geography? All of these can be answered by applying ETL to transform raw datasets into alternative useful views.

**ETL** refers to:

* Extract: Data Extraction (APIS, Websites, PDF Documents). 
* Transform: Data Cleaning (*Important for data analysts*)
* Load: SQlite 3 Databases (Relation Databases: MySQL, Non-retional: MongoDB,Oracle)

Read the cleaned data set and perform further analysis

## Quick ETL Example

While you'll see complete examples and explanations for all of these techniques (and more), here's a quick preview of some ETL techniques covered in this section.

### Import data

In [8]:
# load the pandas library
import pandas as pd
pd.set_option('display.max_colwidth', None)

In [9]:

# read the data and save it to a 'df' variable
df = pd.read_csv('Yelp_Reviews.csv', index_col=0)

# preview the first 5 rows
df.head()

,business_id,cool,date,funny,review_id,stars,text,useful,user_id
1,pomGBqfbxcqPv14c3XH-ZQ,0,2012-11-13,0,dDl8zu1vWPdKGihJrwQbpw,5,I love this place! My fiance And I go here atleast once a week. The portions are huge! Food is amazing. I love their carne asada. They have great lunch specials... Leticia is super nice and cares about what you think of her restaurant. You have to try their cheese enchiladas too the sauce is different And amazing!!!,0,msQe1u7Z_XuqjGoqhB0J5g
2,jtQARsP6P-LbkyjbO1qNGg,1,2014-10-23,1,LZp4UX5zK3e-c5ZGSeo3kA,1,Terrible. Dry corn bread. Rib tips were all fat and mushy and had no flavor. If you want bbq in this neighborhood go to john mulls roadkill grill. Trust me.,3,msQe1u7Z_XuqjGoqhB0J5g
4,Ums3gaP2qM3W1XcA5r6SsQ,0,2014-09-05,0,jsDu6QEJHbwP2Blom1PLCA,5,Delicious healthy food. The steak is amazing. Fish and pork are awesome too. Service is above and beyond. Not a bad thing to say about this place. Worth every penny!,0,msQe1u7Z_XuqjGoqhB0J5g
5,vgfcTvK81oD4r50NMjU2Ag,0,2011-02-25,0,pfavA0hr3nyqO61oupj-lA,1,"This place sucks. The customer service is horrible. They dont serve food unless you order a pizza from a neighboring restaurant. Who does that? They dont control their crowd. Many times I've gone I've seen fights. The bartenders suck - I've almost got in a fight with one because she was a complete bitch. Refused to serve me a drink because she was ""busy"" celebrating her friends birthday BEHIND THE BAR. This place is ridiculous. I will NEVER go there again.. EVER.",2,msQe1u7Z_XuqjGoqhB0J5g
10,yFumR3CWzpfvTH2FCthvVw,0,2016-06-15,0,STiFMww2z31siPY7BWNC2g,5,I have been an Emerald Club member for a number of years. I have always been very satisfied with their vehicles and customer service. This recent visit to Pittsburgh was no exception.,0,TlvV-xJhmh7LCwJYXkV-cg

In [5]:
# find the number of rows and columns
df.shape
print(f'The number of rows are {df.shape[0]} and the number of columns are {df.shape[1]}')

The number of rows are 2610 and the number of columns are 9

In [6]:
# name of columns : check if cleaning is necessary

df.columns

Index(['business_id', 'cool', 'date', 'funny', 'review_id', 'stars', 'text',
       'useful', 'user_id'],
      dtype='object')

In [10]:
# preview the 'text' column

df['text']

1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               I love this place! My fiance And I go here atleast once a week. The portions are huge! Food is amazing. I love their carne asada. They have great lunch specials... Leticia is super nice and cares about what you think of her restaurant. You have to try their cheese enchiladas too the sauce is different And amazing!!!
2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Terrible. Dry corn bread. Rib tips were all fat and mushy and had no flavor. If you want bbq in this neighborhood go to john mulls roadkill grill. Trust me.
4                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       Delicious healthy food. The steak is amazing. Fish and pork are awesome too. Service is above and beyond. Not a bad thing to say about this place. Worth every penny!
5                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         This place sucks. The customer service is horrible. They dont serve food unless you order a pizza from a neighboring restaurant. Who does that? They dont control their crowd. Many times I've gone I've seen fights. The bartenders suck - I've almost got in a fight with one because she was a complete bitch. Refused to serve me a drink because she was "busy" celebrating her friends birthday BEHIND THE BAR. This place is ridiculous. I will NEVER go there again.. EVER.
10                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  I have been an Emerald Club member for a number of years.  I have always been very satisfied with their vehicles and customer service.  This recent visit to Pittsburgh was no exception.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ...
689                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               Came here with my 2 year old daughter for our first date last night.  Halfway through the movie she got tired ad wanted to go home and when the front desk saw us leave, she asked if everything was ok.  We old her what happened and she gave us 2 free passes to come back again!  Awesome!  Clean place, great seating!
4874                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 Great little restaurant. Not to many tables and its byob, which is awesome. We had the Pad Thai and the coconut curry noodles and it was absolutely fantastic. I would absolutely recommend this on a cool day when you want to warm up!
564                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Always great friendly service and fresh baked bread and desserts everyday. \r\n\r\nHighly recommend the custard cakes they are the closest thing I have ever tried to the original Pastéis de Belém in Lisboa  \r\n\r\nThe rice flour cake is also really good and a good option for those whom do not like cake too sweet. \r\n\r\n\r\nThe bean cakes are great here too!  orange, almond, and a few others I have tried are all good. \r\n\r\n\r\nCan't go wrong with Nova Era
3458    We were expecting amazing Thai food after all the reviews that we read and the fact that this place was voted one of the top 100 restaurants in Toronto. \r\n\r\nThis was disappointing. \r\n\r\nFirst off, it was really awkward sitting on the benches outside on the sidewalk, as people walked past us while to wait for our table. \r\n\r\nSecond, when we were seated, it was so loud. It felt like we were in a high school cafeteria. There was so much noise from people talking over each other and from the loud music. We were just happy that we didn't have to share a table with another couple. \r\n\r\nFinally - Food was mediocre. I was extremely disappointed with the curry egg noodle dish. It was awkward to eat and I felt sick about half way through because the curry was too rich. On the flip side - I had a taste of my company's dish and it wasn't that great either - he had the beef stir fry dish with rice. The meat was nice and tender, but it wasn't flavourful. \r\n\r\nWasn't worth the hype, unfortunately.
4206                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Sunday at 8p. Not many people here at all. We were seated for 10-15 min, and no one came to take our drink order. We were nicely greeted at the front though. Guess there was a disconnect between the hostess and waitstaff.
Name: text, Length: 2610, dtype: object

### Apply lambda functions

In [3]:
# use the .map() and lambda function to iterate through the text column and find the length of words per review.

df['Review_Word_Length'] = df['text'].map(lambda x: len(x.split()))
df.head()

,business_id,cool,date,funny,review_id,stars,text,useful,user_id,Review_Word_Length
1,pomGBqfbxcqPv14c3XH-ZQ,0,2012-11-13,0,dDl8zu1vWPdKGihJrwQbpw,5,I love this place! My fiance And I go here atl...,0,msQe1u7Z_XuqjGoqhB0J5g,58
2,jtQARsP6P-LbkyjbO1qNGg,1,2014-10-23,1,LZp4UX5zK3e-c5ZGSeo3kA,1,Terrible. Dry corn bread. Rib tips were all fa...,3,msQe1u7Z_XuqjGoqhB0J5g,30
4,Ums3gaP2qM3W1XcA5r6SsQ,0,2014-09-05,0,jsDu6QEJHbwP2Blom1PLCA,5,Delicious healthy food. The steak is amazing. ...,0,msQe1u7Z_XuqjGoqhB0J5g,30
5,vgfcTvK81oD4r50NMjU2Ag,0,2011-02-25,0,pfavA0hr3nyqO61oupj-lA,1,This place sucks. The customer service is horr...,2,msQe1u7Z_XuqjGoqhB0J5g,82
10,yFumR3CWzpfvTH2FCthvVw,0,2016-06-15,0,STiFMww2z31siPY7BWNC2g,5,I have been an Emerald Club member for a numbe...,0,TlvV-xJhmh7LCwJYXkV-cg,32

In [4]:
df.shape # Previously this was (2610, 9), now we have added a column

(2610, 10)

### Group data

Before you group any data, remember to confirm the data type and ensure it is in the proper/suitable format. That is: the data should be in *categorical format*.

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2610 entries, 1 to 4206
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   business_id  2610 non-null   object
 1   cool         2610 non-null   int64
 2   date         2610 non-null   object
 3   funny        2610 non-null   int64
 4   review_id    2610 non-null   object
 5   stars        2610 non-null   int64
 6   text         2610 non-null   object
 7   useful       2610 non-null   int64
 8   user_id      2610 non-null   object
dtypes: int64(4), object(5)
memory usage: 203.9+ KB

In [15]:
len(df['business_id'].unique())

2192

In [17]:
# preview the number of stars per business_id

df.groupby('business_id')['stars'].mean()

business_id
-050d_XIor1NpCuWkbIVaQ    5.0
-0qht1roIqleKiQkBLDkbw    1.0
-3zffZUHoY8bQjGfPSoBKQ    5.0
-6tvduBzjLI1ISfs3F_qTg    5.0
-9nai28tnoylwViuJVrYEQ    5.0
                         ...
ztP466jMUMtqLwwHqXbk9w    5.0
zw9_mqWBn1QCfZg88w0Exg    5.0
zwNLJ2VglfEvGu7DDZjJ4g    1.0
zzYaAiC0rLNSDiFQlMKOEQ    1.0
zzgSiOnuUjnBnmfR-ZG4ww    5.0
Name: stars, Length: 2192, dtype: float64

In [20]:
df['useful']

1       0
2       3
4       0
5       2
10      0
       ..
689     2
4874    0
564     0
3458    1
4206    0
Name: useful, Length: 2610, dtype: int64

In [21]:
df.groupby('user_id')['useful'].mean() # dataframe.groupby('column_name')['column_to_aggregate'].mean/median/etc()

user_id
-0biHfjE0soSptbU5G3nug    0.0
-2K0yp7lBT_JUOzGkpdJ_g    0.0
-Opvc9hAWllZSSPDUsD7NA    0.0
-Zdxj4wuj4D_899B7tPE3g    0.0
-_iULENf28RbqL2k0ja5Xw    0.0
                         ...
zdG-3ABz7-mv1P3cs2_Rfg    0.0
zpQ76JRDkleW-RQ-U__83g    0.0
zr3d9JdYSBJ0fIJefOqOsQ    0.0
zxCJAztRkzw4kDBxpwKWWg    0.0
zx_Op2OAOM_fRic9tU-jqA    0.0
Name: useful, Length: 1010, dtype: float64

### Check for duplicates

Check how many we have:

In [23]:
df.duplicated().sum()

333

In [6]:
df.duplicated().value_counts()

False    2277
True      333
dtype: int64

In [25]:
# find the duplicated rows by 'business_id'

df[df.duplicated()] #shows rows and columns that are duplicates
df[df.duplicated()].sort_values(by='business_id') #sort values by business_id

,business_id,cool,date,funny,review_id,stars,text,useful,user_id
1729,-GY2fx-8udXPY8qn2HVBCg,0,2016-08-30,0,yQ6P1_CvM94wMLYw1T0UWA,5,Just opened a new account today. So far I am impressed. Nidia was able to coordinate everything via email for my loan and new account which is great with my busy schedule. They were able to get me a lower rate than I was expecting for my new car I also refinanced my current car.,1,sZfZGrI592euyacKUcwQYg
754,-LRlx2j9_LB3evsRRcC9MA,0,2017-10-07,0,kUqPsZmWwLIMSstGHhWssA,5,The vet took the time to explain what was possibly going on with my dog. Staff was friendly. Pricing was good. I will be going back for my vet needs in the future.,0,VgaYZ7004pTwEDSDWR6u4Q
2767,-MKWJZnMjSit406AUKf7Pg,0,2015-01-03,2,rJhrQD3-b9GjTso0dxIkwg,1,Drove 37 miles on a Saturday at 12:30pm for lunch.... to find the place CLOSED! \r\nNOT HAPPY !!!!,0,kzP96uX8TUMmmvLtd-I3RQ
3126,-eIvRc3aEvufstBumpBTPQ,0,2015-07-02,0,rn49y5dm_3sRZ5_LrODFLA,5,After going to several physio clinics over the years with no success i finally found a home. I have bad knees and shoulders and according to the staff I shouldn't be able to walk upright lol. But with sessions from the staff I've already gotten back into all the sports I was used to playing before life took its toll on me. Paul (owner and therapist) is a truly caring individual and does his best to accommodate your schedule. The RMT's are also magnificent and I definitely recommend throwing in a massage session as well.,0,uK0LdXjF93PuPzVgo-Jsgg
2092,-lJtyCOTVInWusU9YF120A,0,2015-11-08,0,qFNtxmCldq0bUoRF1OdpQA,5,One of our favorite Italian restaurants. Fabulous pizza and light & tasty chew pose ravioli that never disappoints. Fabulous friendly staff. A neighborhood gem for casual dining.,0,Ac3vNCPDwirpxSkIwtcvVA
...,...,...,...,...,...,...,...,...,...
3041,ynyDiLHzTdf4du9xMhscxg,0,2015-10-30,0,M-0AaEDTwBSIv_HJu4-pjw,5,Rachael is an artist! I've been going to her for years now and would not trust my brows to anyone else.\r\n\r\nHer studio is warm and relaxing! I recommend Rachael highly.,0,lYXRVN2TJDEVB39G3HzplA
2659,zJGtD3y-pAIGNId4codEEg,1,2013-08-11,1,lwInYPtM4M2jfAftXk-xlA,4,We've been to Otro many times. Stick with the tacos or the chorizo and egg dishes. They are consistently delicious. The margaritas are good. The guacamole is good and sometimes excellent and the chips are crisp. We have had one bad experience there but the situation was immediately addressed by a manager and the bill was graciously adjusted. Service is usually excellent and the atmosphere is cool. Sit at the bar and watch the bartender make drinks - it will give you an appreciation for how hard thy work and what goes into some of their drinks. Didn't care much for the paella but on the whole we like just about everything else. (Sit away from the west facing windows in the late afternoon as it is hot!). This is a perfect place for a casual dinner. The background noise is low so you can enjoy conversation and the food.,1,BjmYO90f7e7oiwyoffC82w
2193,zKw09ftu1730wEIZBZPoFg,3,2015-01-04,0,JV-yxKxMFp-d0rLDc_2_6w,5,So relaxing combined with the meditation and reiki. I'm still floating somewhere out in space. And breathing so much better. This was my first time and I will definitely be back.,5,3mZFkwfa6XV0BBazRTva9w
496,zg5rJfgT4jhzg1d6r2twnA,0,2014-06-21,0,Zbj0HgdN3AT4l-mbH-EfjA,3,Burger week\r\n\r\n1. Blazing Pineapple Burger ($5)\r\n- Decent burger. Good size patty and bun. Only special addition was a grilled slice of pineapple which did add a nice touch to it. The sauce was spicy and can definitely feel the kick after every bite. \r\n\r\nOverall:\r\nNot bad for a quick bite but wouldn't go out of the way to get it.,0,UGW-9bbBEB3eP1o6mWD_WA
988,ziv21pDfyrgdhlrlNIgDfg,0,2016-08-11,0,fus9odxu9bjE2lSxfwNfdw,5,Get this!!! Wow Karlo is amazing and best customer service you could ask for. He installed the antenna and set up all our tv's along with excellent detail explanations and conversation. We will be having my moms house done now next week also. The recoup savings from not having cable is only a few months. Already feels like we are saving money.,2,ywjqPgnMrDZKOhA33v92Cw

Visually inspect them:

In [7]:
# Use keep=False to keep all duplicates and sort_values to put duplicates next to each other
df[df.duplicated(keep=False)].sort_values(by='business_id')

,business_id,cool,date,funny,review_id,stars,text,useful,user_id,Review_Word_Length
1729,-GY2fx-8udXPY8qn2HVBCg,0,2016-08-30,0,yQ6P1_CvM94wMLYw1T0UWA,5,Just opened a new account today. So far I am ...,1,sZfZGrI592euyacKUcwQYg,55
1729,-GY2fx-8udXPY8qn2HVBCg,0,2016-08-30,0,yQ6P1_CvM94wMLYw1T0UWA,5,Just opened a new account today. So far I am ...,1,sZfZGrI592euyacKUcwQYg,55
754,-LRlx2j9_LB3evsRRcC9MA,0,2017-10-07,0,kUqPsZmWwLIMSstGHhWssA,5,The vet took the time to explain what was poss...,0,VgaYZ7004pTwEDSDWR6u4Q,33
754,-LRlx2j9_LB3evsRRcC9MA,0,2017-10-07,0,kUqPsZmWwLIMSstGHhWssA,5,The vet took the time to explain what was poss...,0,VgaYZ7004pTwEDSDWR6u4Q,33
2767,-MKWJZnMjSit406AUKf7Pg,0,2015-01-03,2,rJhrQD3-b9GjTso0dxIkwg,1,Drove 37 miles on a Saturday at 12:30pm for lu...,0,kzP96uX8TUMmmvLtd-I3RQ,18
...,...,...,...,...,...,...,...,...,...,...
2193,zKw09ftu1730wEIZBZPoFg,3,2015-01-04,0,JV-yxKxMFp-d0rLDc_2_6w,5,So relaxing combined with the meditation and ...,5,3mZFkwfa6XV0BBazRTva9w,31
496,zg5rJfgT4jhzg1d6r2twnA,0,2014-06-21,0,Zbj0HgdN3AT4l-mbH-EfjA,3,Burger week\r\n\r\n1. Blazing Pineapple Burger...,0,UGW-9bbBEB3eP1o6mWD_WA,62
496,zg5rJfgT4jhzg1d6r2twnA,0,2014-06-21,0,Zbj0HgdN3AT4l-mbH-EfjA,3,Burger week\r\n\r\n1. Blazing Pineapple Burger...,0,UGW-9bbBEB3eP1o6mWD_WA,62
988,ziv21pDfyrgdhlrlNIgDfg,0,2016-08-11,0,fus9odxu9bjE2lSxfwNfdw,5,Get this!!! Wow Karlo is amazing and best cus...,2,ywjqPgnMrDZKOhA33v92Cw,62
988,ziv21pDfyrgdhlrlNIgDfg,0,2016-08-11,0,fus9odxu9bjE2lSxfwNfdw,5,Get this!!! Wow Karlo is amazing and best cus...,2,ywjqPgnMrDZKOhA33v92Cw,62

### Remove duplicates

In [8]:
df = df.drop_duplicates()
df.shape # Previously this was (2610, 10), now we have dropped duplicate rows

(2277, 10)

### Recheck for duplicates

In [9]:
df.duplicated().value_counts()

False    2277
dtype: int64

In [10]:
# Duplicates should no longer exist
df[df.duplicated(keep=False)].sort_values(by='business_id')

Empty DataFrame
Columns: [business_id, cool, date, funny, review_id, stars, text, useful, user_id, Review_Word_Length]
Index: []

### Create pivot tables

In [11]:
# This transforms the data into a person by person spreadsheet and what stars they gave various restaurants
# Most values are NaN (null or missing) because people only review a few restaurants of those that exist
usr_reviews = df.pivot(index='user_id', columns='business_id', values='stars')
usr_reviews.head()

business_id,-050d_XIor1NpCuWkbIVaQ,-0qht1roIqleKiQkBLDkbw,-3zffZUHoY8bQjGfPSoBKQ,-6tvduBzjLI1ISfs3F_qTg,-9nai28tnoylwViuJVrYEQ,-C8sSrFqaCxp51pyo-fQLQ,-Dnh48f029YNugtMKkkI-Q,-FLnsWAa4AGEW4NgE8Fqew,-G7MPSNBpxRJmtrJxdwt7A,-GY2fx-8udXPY8qn2HVBCg,...,zdE82PiD6wquvjYLyhOJNA,zdd3hyxB8ylYV6RcNe347Q,zg5rJfgT4jhzg1d6r2twnA,ziv21pDfyrgdhlrlNIgDfg,zkhBU5qW_zCy0q4OEtIrsA,ztP466jMUMtqLwwHqXbk9w,zw9_mqWBn1QCfZg88w0Exg,zwNLJ2VglfEvGu7DDZjJ4g,zzYaAiC0rLNSDiFQlMKOEQ,zzgSiOnuUjnBnmfR-ZG4ww
user_id,,,,,,,,,,,,,,,,,,,,,
-0biHfjE0soSptbU5G3nug,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
-2K0yp7lBT_JUOzGkpdJ_g,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
-Opvc9hAWllZSSPDUsD7NA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
-Zdxj4wuj4D_899B7tPE3g,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
-_iULENf28RbqL2k0ja5Xw,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Summary

In this brief introduction, you learned the acronym ETL and got to preview a few examples of ETL processes using pandas.